# -*- coding: utf-8 -*-
"""Bertopic_Final_for_CIA (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OsYi0XQJral-baka7aiezLZNJDkXWH4z
"""

!pip install bertopic

import nltk
nltk.download('stopwords')
nltk.download('punkt')
import pandas as pd
import numpy as np
from bertopic import BERTopic
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import re
from wordcloud import WordCloud
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

import re

# Load the Excel file and extract the text data
data = pd.read_excel('practiceTA.xlsx')
text_data = data['Text'].astype(str).tolist()

from bertopic import BERTopic
from transformers.pipelines import pipeline
from transformers import AutoTokenizer
from sentence_transformers import SentenceTransformer

model_path = "indolem/indobert-base-uncased"
sentence_model = SentenceTransformer(model_path)

text_data = [str(doc) for doc in text_data]
topic_model = BERTopic(embedding_model=sentence_model, verbose=True).fit(text_data)

#show Intertopic Distance Map
topic_model.visualize_topics()

#show Barchart
topic_model.visualize_barchart()

topic_model.get_topic_info().head(10)

# Get topics and their corresponding keywords
topics = topic_model.get_topics()

# Display topics and their keywords
for topic, keywords in topics.items():
    if topic != -1:
        print(f"Topic {topic}:")
        print(", ".join([word for word, _ in keywords]))
        print()